// @koala-append "../../../../lib/jquery/jquery-3.4.1.js"
// @koala-append "../../../lib/bootstrap/4.3.1/js/bootstrap.js"
// @koala-append "../../../../lib/flickity/v2/js/flickity.pkgd.js"
// @koala-append "lib/facebook/pixel/v000001.js"
// @koala-append "../../lib/heatmap/v00001.js"
